### ISSUE TITLE
iriPropertyList

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#100]
There has been talk about creating a parallel to blankNodePropertyList (`[ ... ]`) but where the subject is some specified IRI, instead of a generated Blank Node. Most recently, this was raised by @bblfish recently in other fora. This might look like `[= ... ]`.

A proposed BNF might be `iriPropertyList ::= '[=' iri ';' predicateObjectList ']'`. (Alternatively, create a token IPLSTART ::= '[' WS* '=' and use `iriPropertyList ::= IPLSTART iri predicateObjectList ']'`. Also, add `iriPropertyList` as an alternative for `pathItem`.

For example, the example `[ :firstname "Ora" ] dc:wrote [ dc:title "Moby Dick" ] .` might be re-written as `[= :ora :firstname "Ora" ] dc:wrote [= :mobyDick dc:title "Moby Dick" ] .` which could generate the following triples:

```turtle
<http://example.com/ora> <http://example.com/firstname> "Ora" .
<http://example.com/ora> <http://purl.org/dc/elements/1.1/wrote> <http://example.com/mobyDick> .
<http://example.com/mobyDick> <http://purl.org/dc/elements/1.1/title> "Moby Dick" .
```

The provides a facility similar to JSON-LD for creating embedded statements.

Note that this entails the graph generated without special processing when `=` is interpreted as `owl:sameAs`:

```turtle
_:b0 <http://example.com/firstname> "Ora" .
_:b0 <http://www.w3.org/2002/07/owl#sameAs> <http://example.com/ora> .
_:b0 <http://purl.org/dc/elements/1.1/wrote> _:b1 .
_:b1 <http://purl.org/dc/elements/1.1/title> "Moby Dick" .
_:b1  <http://www.w3.org/2002/07/owl#sameAs> <http://example.com/mobyDick> .
```

I believe there are prior implementations of this, but I don't have a specific reference.

**Comment by TallTed** [comment]
@gkellogg -- For clarity, it's probably worth editing [your initial post](https://github.com/w3c/N3/issues/100#issue-1279011384) and correcting the two instances of `<http://example.com/mobyDick >` (errant space before `>`) to `<http://example.com/mobyDick>`.

**Comment by bblfish** [comment]
The prior implementation is @timbl and @dckc's cwm . I believe the trick was showed to me by @dckc a long time ago (perhaps even around 2005). I use this trick to write my WebID Profile (foaf document) using n3 and then converting it to Turtle, NTriples and RDF/XML.  I was concerned not to generate unnecessary blank nodes with owl:sameAs relations between them - so I tested it carefully. My cwm no longer works right now as cwm has not kept up with phython 3.

I think it would be better to have `[=` as the token. 
 * A tool serialising a graph to N3  would not have a problem  when creating statements such as `[ = <https://.../>  ]` which may otherwise remove the blank node. Semantically this would not be a problem, but it could create problems when working more syntactically with a graph, such as when counting nodes.
 * It gives a way to convert back and forth between json-ld and n3 while keeping the same layout and without loosing desired blank nodes
 
So that would require me to rewrite my card.n3 but that is only 1 regex I need to apply.

**Comment by dckc** [comment]
In that cwm short-hand, `=` was just treated as a property... in particular, `owl:sameAs`, and hence removing the blank-node had a semantic justification. For consistency, a `;` should follow the subject:

```
[= :mobyDick; dc:title "Moby Dick" ] 
```

**Comment by gkellogg** [comment]
Thanks @dckc; yes, of course, a `;` is warranted. Good to know the original reasoning.

**Comment by josd** [comment]
> In that cwm short-hand, `=` was just treated as a property... in particular, `owl:sameAs`, and hence removing the blank-node had a semantic justification. For consistency, a `;` should follow the subject:
> 
> ```
> [= :mobyDick; dc:title "Moby Dick" ] 
> ```

Thank you very much @dckc for the clear explanation!
It motivated me to add it to the EYE running code https://github.com/josd/eye/releases/tag/v22.0622.1937
We now get
```
$ cat moby.n3
@prefix dc: <http://purl.org/dc/terms/>.
@prefix : <http://example.org/nd#>.

[ = :mobyDick; dc:title "Moby Dick" ].
```
```
$ eye --quiet --nope /tmp/moby.n3 --pass 2>/dev/null
@prefix dc: <http://purl.org/dc/terms/>.
@prefix : <http://example.org/nd#>.

:mobyDick dc:title "Moby Dick".
```

**Comment by ericprud** [comment]
If it were defined at the syntactic level, e.g. ```[= :mobyDick dc:title "Moby Dick" ] ``` (no `;`; `[=ID ... ]` is recognized by parser), this could be available to future versions of Turtle. (I kinda regret not pushing for this back when specifying RDF 1.1 Turtle, but we didn't have a community fighting for it.)

```
<#SummerReadingList> a :OrderedListOfBooks ;
  :toRead (
    [= :mobyDick dc:title "Moby Dick"; :setting :WhaleIntestines ]
    [= :jaws dc:title "Jaws"; :setting :Beach ]
  ).
```

The current Turtle limitation encourages representing nodes as BNodes in order to profit from visually-intuitive nesting.

**Comment by bblfish** [comment]
So we have two syntactic construct versions as I see it, and one post-processing one.

The first one is nearly invisible. Someone not looking carefully might not notice the lack of space between `[` and `=`. The confusion is not semantically problematic, since the blank node is identified with a URL. The `[=` is just a helpful shorthand to avoid all the blank node creations.

```Turtle
<#SummerReadingList> a :OrderedListOfBooks ;
  :toRead (
    [= :mobyDick;  dc:title "Moby Dick"; :setting :WhaleIntestines ]
    [= :jaws;      dc:title "Jaws";      :setting :Beach ]
  ).
```  

And this one proposed by @ericp is clearly bringing in a new structure into play, since the turtle generated cannot be parsed without understanding the role of `[=` but it saves a `;` .

```Turtle
<#SummerReadingList> a :OrderedListOfBooks ;
  :toRead (
    [= :mobyDick dc:title "Moby Dick"; :setting :WhaleIntestines ]
    [= :jaws dc:title "Jaws"; :setting :Beach ]
  ).
  ```
  
  Finally, cwm's version does not bring in a new syntax (I think) but adds a post-processing convention that a `[` immediately followed by an `owl:sameAs` written (perhaps?) as `=` does not result in the creation of a blank node followed by an  owl:sameAs to a URI but forgets the owl:sameAs construct. Clearly this must occur before one has a graph, because at that point all order information is lost. 

```Turtle
<#SummerReadingList> a :OrderedListOfBooks ;
  :toRead (
    [ = :mobyDick;  dc:title "Moby Dick"; :setting :WhaleIntestines ]
    [ owl:sameAs :jaws;      dc:title "Jaws";      :setting :Beach ]  //not sure if cwm would remove the [ with this
  ).
 ``` 

The advantage of the 3rd convention is that all current Turtle already syntactically conforms to it. So it's a question whether anything important is lost by the processing convention.
 If something important is lost, then the first or second options that make the processing explicit would be needed. 
 
 @ericprud I guess the first option would with `[= <#x>;` would also work well for a future extension of Turtle?

**Comment by gkellogg** [comment]
I agree, the post-processing step is complicated by the fact that triples are inherently unordered, and blank nodes are typically generated when `[` is seen, so it can be provided when processing objects.

I favor the version of the grammar using the `IPLSTART` token I described above, as this allows existing structures to be interpreted as `iriPropertyList` when there is whitespace between `[` and `=`, which there could be when otherwise processed as a `blankNodePropertyList`, but examples should probably use `[=`.

**Comment by josd** [comment]
In our implementation there is no post-processing step needed.
In the (DCG) grammar rule
`pathitem(Node, Triples) --> ['['], {gensym BN}, propertylist(BN, T), {rewrite BN and T into Node and Triples)}, [']'].`
that rewrite happens for `=` or `owl:sameAs` which can be anywhere in the list of triples `T`.

**Comment by gkellogg** [comment]
> that rewrite happens for `=` or `owl:sameAs` which can be anywhere in the list of triples `T`.

That may be a corner case we should thing about. Are the following all the same?

* `[= :foo ; :p :bar ]`
* `[   = :foo ; :p :bar ]`
* `[ :p :bar ; = :foo ]`

IMO the first two eliminate the blank node, while the later would emit `owl:sameAs` and a bnode.

**Comment by TallTed** [comment]
@bblfish (et al) -- Gotta be careful to codefence all `@foo` constructs (like `@id` in https://github.com/w3c/N3/issues/100#issuecomment-1164875825) here on GitHub, because otherwise people who (probably) have no interest in our conversation get pinged unmercifully.

**Comment by pchampin** [comment]
+1 to have `[=` processed as a special syntactic construct; -1 to have it as some kind of "ad hoc reasoning" that occurs during parsing (separation of concern).

That being said, the double meaning of `=` depending of the context would be confusing...
And as much as I hate breaking backward compatibility: is `=` as an alias of `owl:sameAs` much used "in the wild"? (excluding when it is used to substitute a  bnode with an IRI, obviously...)

**Comment by afs** [comment]
Overloading  `=` for `owl:sameAs`, then a semantic interpretation, with using `[=` as special syntax seems to produce some odd visual situations. 

`[= ex:me; :p 123 ]` is one triple but `ex:me = [:p 123 ].` is two. `[= ex:me]` is zero triples. `[ = ex:me]` is one triple. One space difference and it is a different graph.

`[= ex:me]` is illegal if `;` is mandatory but  `[ = ex:me ]` is legal.

`[] = ex:me .` is natural in Turtle. 
Having `[ :p 123 ] = ex:me` being two triples and `[= ex:me] :p 123 ` being one is confusing.
`ex:me=[]` but not `[ex:me =]`.

Keeping it as a semantic conclusion as in cwm and Eye keeps it clean.

For special syntax, using a new marker seems much clearer as the goal is human authoring of data.
Keeping it separate with maybe `:=` or a keyword stops these unexpected (to some) outcomes.

`ex:me := [ :p 123 ]`.
`ex:me in [ :p 123 ]`.
`[ with ex:me ; :p 123 ]`.
`using ex:me [ :p 123; ... ]`

What about the effect on output? In N-triples?

If the data has 

```
_:a owl:sameAs ex:me .
_:a :p 123 .
```

should it always print as `[= ex:me;:p 123]`?

**Comment by bblfish** [comment]
> If the data has
> 
> ```
> _:a owl:sameAs ex:me .
> _:a :p 123 .
> ```
> 
> should it always print as `[= ex:me;:p 123]`?

I don't think that is a problem, any more than it is a problem that one can write the graph in an indefinite number of ways including the two above. For example the blank nodes can be named any number of ways, eg `_:b` or `_:c` or ... , there can be white space between the lines or not, the indents can be done with tabs or any number of spaces, ... These are user selectable parameters for how the output should look. If the N3 is for human consumption then it would make sense for the serialisation algorithm to spend energy on an optimal presentation that includes `[= <#node>; ... ] where that allows linked data to come more closely together. In other circumstances that may not be what is desired. 

> [= ex:me; :p 123 ] is one triple but ex:me = [:p 123 ]

One could think of other options. Perhaps `[== ex:me; :p 123 ]` would make things clearer?

**Comment by afs** [comment]
`with` and `using` are inspired by various programming languages which have a syntax form applies some implicit context for the block. Maybe other words would work.

`==` is equals in many places so I'm not inspired by the choice.

Something directional would be good because the syntax relationship isn't symmetrical.

Delimiters pairs are in short supply 😄.

**Comment by bblfish** [comment]
(a bit of an aside) 

@william-vw wrote
> Note that ordering of triples does not matter in RDF

@gkellogg wrote
>  post-processing step is complicated by the fact that triples are inherently unordered

I think there is a mistake being made here. Serializations and deserializations are inherently ordered, whereas graphs are inherently unordered. Serialization means putting in a series, in an order. Any graph with `n` triples can serialized into `n!` (n factorial) lists of triples. 

I think the right way to model a deserialization function is one that takes as input a stream of bytes and outputs a stream of Triples or Quads and optionally namespaces (depending on the format). There are many situation where one does not want to turn the stream of Quads into a Graph such as 

 * one may want to immediately serialize the stream back to another format. e.g. turn n3 into json-ld. Keeping is often the right thing to do
 * there may be reason to filter the stream before it reaches its destination
 * one may want to pass the stream onto a DB engine
 * streams use a lot less memory than graphs.

Similarly before serializing a graph, an intermediate process to order the graph is often needed. For example to test the output serialization one has to have a deterministic ordering for a graph. 

The point of this is that it is at that intermediate stage there is an order, so one should know which the first url following a blank node is.

**Comment by william-vw** [comment]
> I think there is a mistake being made here. Serializations and deserializations are inherently ordered, whereas graphs are inherently unordered. Serialization means putting in a series, in an order. Any graph with n triples can serialized into n! (n factorial) lists of triples.

The issue here is that `[ = :foo ; :p :bar ]` is identical to `[ :p :bar ; = :foo ]`, when not considering `[=` as a token, are semantically equivalent, regardless of any (de)serialization considerations. IMO introducing a triple ordering for this purpose would open up a whole can of worms. (Note there is another complication: a later `= :foo` within `[]` changes the meaning of a prior `:p :bar` in the same `[]`, which I believe is also problematic in RDF.)

> I think this may be an example of "if it ain't broke, don't fix it", and we should reject this proposed change.

I agree that a whole bunch of corner cases complicate matters here. IIUC the goal is a shorthand for describing triple objects in place - I still think this could be very useful. But maybe we're overly focusing on (ab)using two existing notations (i.e., `[]` and `=`) to achieve this goal.

As a possible alternative, I vaguely remember a now extinct query language (SeRQL) allowing a [combination of path expressions and branching](http://archive.rdf4j.org/users/ch11.html#figure-serql-branch2) for this purpose. But, I don't think we can easily apply our resource path syntax here. E.g., the [example](http://ppr.cs.dal.ca:3002/n3/editor/s/isLE8hus):
```
:first!:pred :pred1 :obj1 ;
    :pred2 :obj2 .
```
Would be interpreted as:
```
<http://n3-editor.org/first> <http://n3-editor.org/pred> _:bn_1.
_:bn_1 <http://n3-editor.org/pred1> <http://n3-editor.org/obj1>.
_:bn_1 <http://n3-editor.org/pred2> <http://n3-editor.org/obj2>.
```

I.e., `:pred2` would not describe `:obj1`. But maybe the solution could lie in this direction?

**Comment by josd** [comment]
As discussed in [today's CG meeting](https://docs.google.com/document/d/1A3HAUhjaVnnJ6yVbFAvIBRJQjUY9aFlQ2_bGxkD0mnE/edit) I have implemented the proposed solution in the [latest EYE](https://github.com/josd/eye/releases/tag/v22.0627.1819) and this is what we currently get:
```
$ cat issue100.n3
@prefix dc: <http://purl.org/dc/terms/>.
@prefix : <http://example.org/nd#>.

[ id :mobyDick dc:title "Moby Dick" ].

<#SummerReadingList> a :OrderedListOfBooks ;
  :toRead (
    [ id :mobyDick dc:title "Moby Dick"; :setting :WhaleIntestines ]
    [ id :jaws dc:title "Jaws"; :setting :Beach ]
  ).

```
```
$ eye --quiet --nope /tmp/issue100.n3 --pass 2>/dev/null
@prefix dc: <http://purl.org/dc/terms/>.
@prefix : <http://example.org/nd#>.

:mobyDick dc:title "Moby Dick".
:jaws dc:title "Jaws".
<file:///tmp/issue100.n3#SummerReadingList> a :OrderedListOfBooks.
<file:///tmp/issue100.n3#SummerReadingList> :toRead (:mobyDick :jaws).
:mobyDick :setting :WhaleIntestines.
:jaws :setting :Beach.
```

**Comment by bblfish** [comment]
I think there was a quick brain-storm  where `id` was thought to be preferable as it was shorter. (I guess the best name is still open for debate)

**Comment by gkellogg** [comment]
Okay, I missed that I'll update my implementation.

**Comment by gkellogg** [comment]
Implemented, but not released in https://github.com/ruby-rdf/rdf-n3/commit/a55d2ffecc58a34c320d3cd523bc11bf953daef7. Some tests I'll add for the spec:

    describe "iriPropertyList" do
      {
        "not embedded": [
          %([id :s :p :o] .),
          %(:s :p :o .)
        ],
        "with whitespace": [
          %([ id :s :p :o] .),
          %(:s :p :o .)
        ],
        "with linefeed": [
          %([
            id :s
            :p :o
           ] .),
          %(:s :p :o .)
        ],
        "as a single object": [
          %(
            @prefix a: <http://foo/a#> .
            a:b a:oneRef [
              id a:node0
              a:pp "1" ;
              a:qq "2"
            ] .
          ),
          %(
            <http://foo/a#node0> <http://foo/a#pp> "1" .
            <http://foo/a#node0> <http://foo/a#qq> "2" .
            <http://foo/a#b> <http://foo/a#oneRef> <http://foo/a#node0> .
          )
        ],
        "nested resources": [
          %(
            @prefix a: <http://foo/a#> .

            a:a a:p [
              id a:node1
              a:p2 [
                id a:node0
                a:p3 "v1" , "v2" ;
                a:p4 "v3" ] ;
              a:p5 "v4" ] .
          ),
          %(
            <http://foo/a#node0> <http://foo/a#p3> "v1" .
            <http://foo/a#node0> <http://foo/a#p3> "v2" .
            <http://foo/a#node0> <http://foo/a#p4> "v3" .
            <http://foo/a#node1> <http://foo/a#p2> <http://foo/a#node0> .
            <http://foo/a#node1> <http://foo/a#p5> "v4" .
            <http://foo/a#a> <http://foo/a#p> <http://foo/a#node1> .
          ),
        ],
        "illegal semicolon": [
          %([ id :s ; :p :o]),
          :error
        ],
        "illegal subject list": [
          %([ id :s1, :s2 :p :o]),
          :error
        ],
        "illegal bnode subject": [
          %([ id _:bn :p :o]),
          :error
        ],
      }.each do |title, (n3, res)|
        it title do
          if res == :error
            expect {
              parse(n3, base_uri: "http://a/b", validate: true)
            }.to raise_error(RDF::ReaderError)
          else
            expected = RDF::Graph.new {|g| g << RDF::N3::Reader.new(res, base_uri: "http://a/b")}
            expect(parse(n3, base_uri: "http://a/b")).to be_equivalent_graph(expected, logger: logger, format: :n3)
          end
        end
      end
    end

**Comment by bblfish** [comment]
I updated my card.n3 to use `[ id <...>...]` and that did not work with eye. But `[id <...>` did`.  I then transformed it to turtle

```sh
eye --quiet --nope card.n3 --pass 2>/dev/null | rapper -i turtle -o turtle - https://bblfish.net/people/henry/card > card.ttl
```
and published it 

```sh
$ curl -Li -H "Accept: text/rdf+n3" https://bblfish.net/people/henry/card | less
$  curl -Li -H "Accept: text/turtle" https://bblfish.net/people/henry/card | less
```

**Comment by josd** [comment]
Could you give a concrete example that did not work with eye?
I tried
```
$ cat test_id.n3
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<https://bblfish.net/people/henry/card>
    foaf:knows
        [ id <https://www.w3.org/People/Berners-Lee/card#i> a foaf:Person;
            foaf:name "Tim Berners Lee";
        ],
        [
          id <https://pietercolpaert.be/#me> a foaf:Person;
            foaf:name "Pieter Colpaert"
        ].
```
and it worked perfectly well:
```
$ eye --nope test_id.n3 --pass 2>/dev/null
#Processed by EYE v22.0628.0950 josd
#eye --nope test_id.n3 --pass

@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<https://bblfish.net/people/henry/card> foaf:knows <https://www.w3.org/People/Berners-Lee/card#i>.
<https://bblfish.net/people/henry/card> foaf:knows <https://pietercolpaert.be/#me>.
<https://www.w3.org/People/Berners-Lee/card#i> a foaf:Person.
<https://pietercolpaert.be/#me> a foaf:Person.
<https://www.w3.org/People/Berners-Lee/card#i> foaf:name "Tim Berners Lee".
<https://pietercolpaert.be/#me> foaf:name "Pieter Colpaert".

#2022-06-29T12:57:49.751Z in=6 out=6 ent=0 step=0 brake=1 inf=20941 sec=0.041 inf/sec=510756
#ENDS
```
