### ISSUE TITLE
Built-ins

### ISSUE THREAD

**Issue by doerthe** [w3c/N3#11]
Based on the discussion we had with issue #9 , I think we shoulc also have a look into the built-in we need. A good starting point would be to see whether or not we find [what Cwm has](https://www.w3.org/2000/10/swap/doc/CwmBuiltins) useful.
log:implies is useful and out of question for me. 

But what about the other predicates on the list? Do we need them? What else would we need?

**Comment by mielvds** [comment]
This is also a matter of scoping the work of the N3 spec (or at least the N3 Core spec) and usability. A real builtin vocabulary can be standardized independently (in or out the group) and some can even be reused as [SPARQL extensionFunction](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#extensionFunctions). 
To me, a builtin is always implementation specific, meaning you are not guaranteed your reasoner can deal with it. Of course, you can force compliance in the spec, but then they are simply constructs of N3.

Debatable rule of thumb: if your builtin is not worth creating shorthand for in the syntax, then it shouldn't be in your core standard. 

A shorthand can be as simple as not having a prefix; e.g., `isIRI` in SPARQL. But of course:

- what's the minimum set needed (`log:implies`seems obvious)?
- what's the relation with for example SPARQL extensionFunction? Can we piggyback somewhere on semantics defined elsewhere, e.g., like already with `log:`?
- what are possible prefixes?

**Comment by william-vw** [comment]
(moving this from the "[closing the world](https://github.com/w3c/N3/issues/9)" discussion)

Nevertheless I feel that it would be useful to support a set of core predicates in the standard N3 spec (e.g., lists and logic! also math, string, time) _that would make the difference between N3 being just another run-of-the-mill rule language_ to something that is highly **usable** and **effective** for many real-world purposes. 

Rather than making them part of separate standards documents, I would propose including these core operators in the N3 standard to ensure they are available to all potential N3 developers. Of course, since that puts pressure on developers to support all these predicates if they want to claim compatibility with the core N3 spec, so care must be taken that the spec isn't unrealistically demanding.

Perhaps it wouldn't be a bad idea to create a wish-list of N3 predicates that people would like to see supported as a file in the Git repo. Anyone can edit the list and add their support or reservations to a proposed predicate. In case of controversy or need for discussion, a separate issue could be started on the particular N3 predicate.

I made an initial attempt [here](https://github.com/w3c/N3/blob/master/builtins.txt). I copied relevant parts of descriptions from the respective sources. Note that the initial list is only based on the Cwm builtins. It's a bit of a long list but I feel that all of them are quite useful. Please feel free to update, comment or extend with other predicates.

**Comment by gkellogg** [comment]
Note that `log:semantics` and `log:includes` share some commonality with [SPARQL FROM and FROM NAMED](https://www.w3.org/TR/sparql11-query/#namedGraphs), and in general the world has moved on from specifying the semantics of different RDF representations explicitly to use content-negotiation and semantics defined by their respective media types.

**Comment by mielvds** [comment]
> Nevertheless I feel that it would be useful to support a set of core predicates in the standard N3 spec (e.g., lists and logic! also math, string, time) _that would make the difference between N3 being just another run-of-the-mill rule language_ to something that is highly **usable and effective** for many real-world purposes.
> 
> Rather than making them part of separate standards documents, I would propose including these core operators in the N3 standard to ensure they are available to all potential N3 developers. Of course, since that puts pressure on developers to support all these predicates if they want to claim compatibility with the core N3 spec, so care must be taken that the spec isn't unrealistically demanding.

Seems like we are on the same page here. Doesn't this discussion also depend on whether we decide to stay in FOL or not?

> 
> Perhaps it wouldn't be a bad idea to create a wish-list of N3 predicates / constructs that people would like to see supported as a file in the Git repo. Anyone can edit the list and add their support or reservations to a proposed predicate / construct. In case of controversy or need for discussion, a separate issue could be started on the particular N3 predicate. (To me a construct is something like `@forAll` and a predicate something like `log:implies`).
> 
> I made an initial attempt [here](https://github.com/w3c/N3/blob/master/predicates_constructs.md). 

It's useful to link real use cases to these wishes to allow newcomers to get into the rationale and also to assess the priority. Do we have a use case document already?

**Comment by william-vw** [comment]
> It's useful to link real use cases to these wishes to allow newcomers to get into the rationale and also to assess the priority. Do we have a use case document already?

Yes I added some use cases to new predicates / constructs in the file (i.e., that are not part of the Cwm list of builtins). Everybody should feel free to add use cases to the others as well.

**Comment by doerthe** [comment]
To also keep this thread up to date, I would like to add here that we have a built-in which list: https://docs.google.com/document/d/1_YiM6DHbsQ6SEo5mzbGh2bDubAM04kziXozLt1qs76M/edit?usp=sharing

**Comment by william-vw** [comment]
since we have a separate wish-list of builtins on google drive, will close this issue.
