### ISSUE TITLE
build-ins spec

### ISSUE THREAD

**Issue by domel** [w3c/N3#116]
@tduval-unifylogic , @william-vw I see that there is traffic on the repo regarding build-ins. That's great! But I see that only the old build-ins are being formalized. Didn't we forget about the new ones we discussed many months ago?

**Comment by william-vw** [comment]
@domel Can you please list the builtins that we missed?

**Comment by domel** [comment]
Accordint to [N3 Buildin Extensions](https://docs.google.com/document/d/1pIcBPiRMxU9HzY5NllXj4xsoYHaI4bVeHs1pmxkIYzM/edit?usp=sharing):
- sha2-224
- sha2-256
- sha2-384
- sha2-512
- sha3-224
- sha3-256
- sha3-384
- sha3-512
- cos
- cosh 
- sin
- sinh
- tan
- tanh
- atan2
- degrees
- indexOf
- subList
- reverse
- sort
- min
- max
- avg
- std
- Set operators (union, intersect, except)
- equalTo
- notEqualTo
- lessThan
- greaterThan
- notLessThan
- notGreatherThan
- indexOf
- length
- substring
- contains
- toUpperCase
- toLowerCase
- equalIgnoringCase
- notEqualIgnoringCase
- containsIgnoringCase
- startsWith
- endsWith
- concatenation
- scrape
- format
- replace
- semanticsOrError 
- rawType
- n3String 
- Chaff
- N3Document
- Formula
- String
- List
- Other
- Truth
- Falsehood
- sameTerm
- isIRI
- isURI
- isBlank
- isLiteral
- UUID
- STRUUID
- lang
- datatype
- URITemplate
- racine
- rawUri
- graphDifference
- graphIntersection
- graphList
- conjunction
- graphMember
- graphPair

**Comment by william-vw** [comment]
@domel this targets an intersection of builtins supported by all three reasoners (jen3, eye, cwm) - this is what we currently consider the "core" set of builtins. 

It is true that what is considered "core" is still not fully fixed by the CG, but at this point we would like to get some progress without getting bogged down with that discussion..

But, please feel free to contribute other builtin descriptions based on [`fno-builtins.n3`](https://github.com/w3c/N3/blob/feature-core-builtin-specs/useOfBuiltins/core-specs/03-development/site/spec-builtins/fno-builtins.n3).

**Comment by domel** [comment]
Yes, but maybe we should expand the "core" at least with those buildins that are very simple to implement. I am thinking of crypto and math. For example, sha2 (in different variants) can be implemented at least as simple as sha2.

**Comment by william-vw** [comment]
@domel Indeed - please feel free to add these to the aforementioned file (if the format is unclear please let us know and we can clarify).
