### ISSUE TITLE
slash vs hash

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#131]
- I think that `http://www.example.org/#` should be corrected to use slash or hash, but not both. Slash is preferred for collections of individuals, whereas hash can only be used for ontologies of relatively few terms.
- In addition, https://w3c.github.io/N3/spec/#relative-iri-example has a mistake: I think it would result in `##` in resolved IRIs, which is invalid.

**Comment by domel** [comment]
> * Slash is preferred for collections of individuals, whereas hash can only be used for ontologies of relatively few terms.

Any reference for that statistics? See https://www.w3.org/wiki/HashVsSlash

**Comment by TallTed** [comment]
It's not quite that "hash can _only_ be used for ontologies of relatively few terms" as that dereferencing hash-based URIs that identify fragments in large resources (ontologies or otherwise) can be difficult and is always inefficient use of network infrastructure, relative to slash-based URIs that dereference to the entirety of a small resource.

In other words, I would say that hash are *preferred* only for resources containing relatively few fragments, including ontologies of relatively few terms.
