### ISSUE TITLE
Path syntax

### ISSUE THREAD

**Issue by mielvds** [w3c/N3#22]
Continuing from #21 on how to incoporate path expressions in the N3 syntax. There is already a [path syntax](https://www.w3.org/TeamSubmission/n3/#path) in the team submission, for instance to traverse properties in the inverse direction, e.g., (based on N3 spec): :nancy^fam:hasMother (anyone who has nancy as mother). 

To be discussed here:
1. Do we update the syntax to be compatible with [SPARQL Property Paths](https://www.w3.org/TR/sparql11-query/#propertypaths)?
2. How much of SPARQL PP do we incorporate? Can/Do we add full compatibility?
3. Do we keep the current path expressiveness or do we limit to property paths as well?

**Comment by william-vw** [comment]
> Do we keep the current path expressiveness or do we limit to property paths as well?

Note that it seems like the N3 path syntax was meant to start from a resource instead of a property; see [the examples](https://www.w3.org/TeamSubmission/n3/#path) in the N3 spec. This seems reflected by the N3 BNF since it only allows inverting after the first item (see #23)

So when used for _property paths_, the current N3 path syntax would not allow inverting the first property in the path. This means that, even when limited to the `^` operator, N3 property paths would not be as expressive. At least, in the current N3 syntax.

**Comment by william-vw** [comment]
> Do we update the syntax to be compatible with SPARQL Property Paths?
> How much of SPARQL PP do we incorporate? Can/Do we add full compatibility?

Supporting the entire SPARQL property path syntax sounds like a neat N3 extension :) But I'm unsure whether it should be part of the core N3 at this point

**Comment by william-vw** [comment]
In line with our prior discussion here, the community group decided to leave full support SPARQL property paths as an N3 extension

But, note that we aim to extend the N3 path syntax to allow inverse properties at any position in a path (see issue [here](https://github.com/w3c/N3/issues/23)), which goes towards supporting general property paths.
