### ISSUE TITLE
LANGTAG confused with @is and @has

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#32]
Suggest the following rule update:

    [145s] LANGTAG                          ::= "@" ([a-zA-Z]+ ( "-" [a-zA-Z0-9]+ )*) - ("is" | "has")

Otherwise, an example like `"value" @is :prop :of :a` can consume `"value" @is` as a language-tagged string.

I actually implement it using the following negative-look ahead Regular Expression:

    /@(?!(?:is|has))(?:[a-zA-Z]+(?:-[a-zA-Z0-9]+)*)/

I don't think there are any other cases where `@` keywords would come right after a string.

The original N3 parser required this to be handled in the tokenizer, IIRC.

**Comment by josd** [comment]
Excellent catch and Cwm works fine for
`"value" @is :prop @of :a.`
but EYE didn't and this is now fixed in
https://github.com/josd/eye/releases/tag/v20.0716.2304

**Comment by gkellogg** [comment]
Of course, this has unfortunate consequences for tagging strings in Icelandic. “fyrirgefðu”@is.

**Comment by pchampin** [comment]
> Of course, this has unfortunate consequences for tagging strings in Icelandic. “fyrirgefðu”@is.

It would indeed be much unfortunate if N3 could not represent *all* possible RDF graphs. Isn't there another way?

For example, why not forbid white spaces between literal value and language tag?
Granted, it would introduce an incompatibility with Turtle, which allows it.
But honestly, I never saw any Turtle literal with space before the language tag,
and I was not even aware that it was allowed,
so I don't think this incompatibility would be much harmful in practice -- less harmful than banning some language tags, anyway.

**Comment by william-vw** [comment]
Good points all. I think there are multiple options, some more preferable than others:
- Having a context-sensitive grammar would likely solve it but be an egregious overkill. 
- Having a pseudo-code "meta" parser rule in the spec that enforces the duality of `@is - @of` in N3 statements. This would have to be manually implemented in each system. More of a poor-man's version of a context-sensitive grammar rule :-) 
- As @pchampin's suggestion, disallowing a space between the language string and language tag. But, this would break conformance with Turtle, although, as @pchampin said, I also didn't know that a space was even allowed there.
- Sidestep the whole issue by dropping support for `@is - @of` and `@has`. We've had a discussion about how these are not very useful anyway (and currently redundant, since the introduction of `^` for inverting a predicate). See #23. But, in the end decided to keep them. We could revisit that decision.

**Comment by gkellogg** [comment]
It's not just conformance with Turtle, but with EBNF, which has whitespace rules that both Turtle and N3 follow. It's only in the context of terminals that whitespace is mandated. The rule using LANGTAG is:

    [25] rdfLiteral                         ::= STRING (LANGTAG | '^^' iri)?

We'd need to break this down into something like the following:

    rdfLiteral ::= LANGSTRING | (STRING '^^' iri) | STRING
    LANGSTRING ::= STRING LANGTAG

Alternatively, we could not support `@is :pred @of` and use the `@`-less variation `is :pred of`. This risks some breakage with the previous N3, but it would have supported `is` as a PNAM_LN, which (IIRC) could be used as a QName without a preceding `:`, which we also don't support.

**Comment by gkellogg** [comment]
I changed the following EBNF to address this:

```
[12] verb                               ::= predicate
                                          | 'a'
                                          | 'has' expression
                                          | 'is' expression 'of'
                                          | '<-' expression # Synonym for is expression of
                                          | '<='
                                          | '=>'
                                          | '='
[14] predicate                          ::= expression
[33] BOOLEAN_LITERAL                    ::= 'true' | 'false'
```
