### ISSUE TITLE
Numeric interpretation of plain literals

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#47]
There are a number of cases where the math functions operate on plain literals (e.g., `{ ("3" "5") math:sum :x } => { :x :valueOf "3 + 5" } .`. Typically, these have the form of integers, but that might not always be the case. Do we define how to interpret plain literals as numbers? We could use the `numericLiteral` production to intuit this, which has precedent in `log:semantics`. We should define it, though.

**Comment by gkellogg** [comment]
Similarly, we should define how a processor should behave when a literal does not parse as any of double, decimal, or integer, or if just a prefix of the literal parses that way.

**Comment by gkellogg** [comment]
I could see something like a `math:cast` operator (like SPARQL STRDT) doing something like the following:

`{("1" xsd:integer) log:STRDT ?x} => {:result :is ?x} .`

resulting in `:result :is 1 .`.

It would also be useful to be able to extract the datatype or language or a literal
```turtle
{ 1.1 log:datatype ?y } => {1.1 :datatype ?y } .
```

resulting in `1.1 :datatype xsd:decimal .`.

Other functions from [SPARQL Functions on RDF Terms](https://www.w3.org/TR/sparql11-query/#func-rdfTerms) would also be useful:

* `isIRI`
* `isBlank`
* `isLiteral`
* `isNumeric`
* `str`
* `lang`
* `datatype`
* `IRI`
* `BNODE`
* `STRDT`
* `STRLANG`

They might even be bi-directional.

**Comment by pchampin** [comment]
:+1: for `math:cast`.

---

However, I am not in favour of `isIRI`, `isBlank`, `isLiteral`. These SPARQL functions apply to the *syntax*, not the semantics. So stating something like
```turtle
<http://champin.net/#pa> log:isIRI true.
```
violates the [use/mention distinction](https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction). “I am not an IRI, I'm a free man!” :stuck_out_tongue_winking_eye: 
Put it another way, what would you expect from the following?
```turtle
:answer = 42.
{ :answer log:isLiteral ?x } => { :test1 :gave ?x }.
{ 42 log:isIRI ?x } => { :test2 :gave ?x }.
```
---

`log:datatype` may raises a similar problem (depending how we consider it).
What would you expect from the following?
```turtle
{ "42"^^xsd:integer log:datatype ?x } => { :test3 :gave ?x }.
```
Should this return only `xsd::integer`, or also `xsd:decimal` (which, according to [XSD](https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes), is the base type of `xsd:integer`)?

Also, note that, according to [RDF Semantics](https://www.w3.org/TR/rdf11-mt/#rdfsemcond3), any literal is linked to its datatype(s) by `rdf:type`. So should we reuse `rdf:type` rather than introducing a new predicate `log:datatype`?

**Comment by william-vw** [comment]
We talked during the last meeting about the utility of `log:dtlit` (as opposed to `rdf:type`). 
Also, I believe we will follow the XPath rules on casting to numerals - which includes casting "123" as integer if needed.

Thoughts?
