### ISSUE TITLE
use of the <#> namespace for the tests in https://w3c.github.io/N3/tests/N3Tests/manifest-reasoner.ttl

### ISSUE THREAD

**Issue by josd** [w3c/N3#65]
Most of the tests in https://w3c.github.io/N3/tests/N3Tests/manifest-reasoner.ttl have mf:action and mf:result which both use the <#> namespace and so <#abc> in mf:action does not corefer with <#abc> in  mf:result.
They should rather use for instance <test#> or an absolute uri.

**Comment by gkellogg** [comment]
Is this a problem in the manifest itself, or in some specific test result files? Can you provide an example of where this doesn’t produce the right results?

**Comment by josd** [comment]
The problem is in the files mentioned in the manifest e.g. https://w3c.github.io/N3/tests/N3Tests/cwm_includes/list-in.n3 is (implicitly) using `@prefix : <#> .` and https://w3c.github.io/N3/tests/N3Tests/cwm_includes/list-in-ref.n3 is also using `@prefix : <#> .` so `:Pythagorean` in the former is not the same as `:Pythagorean` in the latter.
The problem seems to be in many entries and I guess it stems from making a copy as -ref.n3 files from the cwm result.

**Comment by gkellogg** [comment]
Yes, that's indeed, not the typical pattern for these tests. list-in-ref should have `@prefix : <list-in.n3#> .`

It was hidden in my test runner as I set the base of the expected file to the action file, but this is probably not appropriate.

I'll see what needs to be addressed and update PR #61. Otherwise, there will be a number of conflicts.
